version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    AWS_ACCOUNT_ID: 339712963357
    IMAGE_REPO_NAME_FRONTEND: mlops/frontend
    IMAGE_REPO_NAME_YOLO: mlops/yolo-backend
    IMAGE_REPO_NAME_DEPTH: mlops/depth-backend
    IMAGE_TAG: prod
    # Production URLs from your Terraform deployment
    REACT_APP_YOLO_API_URL: http://mlops-alb-1724185036.us-east-1.elb.amazonaws.com/yolo
    REACT_APP_DEPTH_API_URL: http://mlops-alb-1724185036.us-east-1.elb.amazonaws.com/depth

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Build started on $(date)"

      # Build frontend with production environment variables
      - echo "Building frontend image with production API URLs..."
      - cd ./object-detection-react-app
      - echo "REACT_APP_YOLO_API_URL=$REACT_APP_YOLO_API_URL" > .env.production
      - echo "REACT_APP_DEPTH_API_URL=$REACT_APP_DEPTH_API_URL" >> .env.production
      - docker build --build-arg REACT_APP_YOLO_API_URL=$REACT_APP_YOLO_API_URL --build-arg REACT_APP_DEPTH_API_URL=$REACT_APP_DEPTH_API_URL -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_FRONTEND:$IMAGE_TAG .
      - cd ..

      - echo "Building YOLO backend image..."
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_YOLO:$IMAGE_TAG ./yolo-v5-flask-app

      - echo "Building Depth backend image..."
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_DEPTH:$IMAGE_TAG ./depth-anything-flask-app

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker images to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_FRONTEND:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_YOLO:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_DEPTH:$IMAGE_TAG
      - echo "All images pushed successfully!"

artifacts:
  files:
    - "**/*"
